[package]
name = "snk"
version = "0.1.0"
authors = ["sdttttt <760159537@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
async-trait = "0.1.31"